Lab/Weterynarze/Weterynarze/Weterynarze/Controllers/VetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Weterynarze.Data;
using Weterynarze.Models;
using System.Data;
using System.Drawing;
using Newtonsoft.Json.Linq;

namespace Weterynarze.Controllers
{
    public class VetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Vets
        public async Task<IActionResult> Index()
        {
            return _context.Vet != null ?
                        View(await _context.Vet.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vet'  is null.");
        }

        public async Task<IActionResult> Location()
        {
            return _context.Vet != null ?
                        View(await _context.Vet.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vet'  is null.");
        }

        public async Task<IActionResult> ClinicLocation()
        {
            return _context.Vet != null ?
                        View(await _context.Vet.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vet'  is null.");
        }

        public async Task<IActionResult> New()
        {
            return _context.Vet != null ?
                        View(await _context.Vet.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vet'  is null.");
        }

        [HttpGet]
        public IActionResult GetCoordinates(string searchText)
        {
            string apiKey = "chDMQRlDRv0KngLYo3sXcOtNBESgx1eEU199e4Z1B7U";
            //Console.WriteLine($"searchText: {searchText}");
            string apiUrl = $"https://geocoder.ls.hereapi.com/6.2/geocode.json?searchtext={searchText}&gen=9&apiKey={apiKey}";



            try
            {
                // Wykonanie zapytania HTTP do usługi API
                using (var client = new System.Net.WebClient())
                {


                    string responseJson = client.DownloadString(apiUrl);
                    JObject responseObject = JObject.Parse(responseJson);
                    JToken view = responseObject["Response"]["View"][0];
                    JToken result = view["Result"][0];
                    JToken location = result["Location"]["DisplayPosition"];

                    double latitude = location.Value<double>("Latitude");
                    double longitude = location.Value<double>("Longitude");

                    //Console.WriteLine($"latitude: {latitude}");
                    //Console.WriteLine($"longitude: {longitude}");

                    // Zwrócenie wyników jako JSON
                    var coordinates = new { latitude, longitude };

                    //Console.WriteLine($"coordinates: {coordinates}");

                    return Json(coordinates);
                }
            }
            catch
            {
                return Json(null); // W przypadku błędu zwróć null lub odpowiednią informację
            }
        }

        /*
        public string getCoordinatesFromAddress(string addr)
        {
            var url = "https://geocoder.ls.hereapi.com/6.2/geocode.json?searchtext=" +
                    addr +
                    "&gen=" + 9 +
                    "&apiKey=chDMQRlDRv0KngLYo3sXcOtNBESgx1eEU199e4Z1B7U";


            var request = WebRequest.Create(url);

            using (WebResponse wrs = request.GetResponse())
            {
                using (Stream stream = wrs.GetResponseStream())
                {
                    using (StreamReader reader = new StreamReader(stream))
                    {
                        string json = reader.ReadToEnd();
                        var obj = JObject.Parse(json);
                        string Latitude = (string)obj["Latitude"];
                        string Longitude = (string)obj["Longitude"];

                       
                        return (Latitude + Longitude);
                    }
                }
            }

        }*/






        public static string CityStateCountByIp(string IP)
        {
            //var url = "http://freegeoip.net/json/" + IP;
            //var url = "http://freegeoip.net/json/" + IP;
            string url = "http://api.ipstack.com/" + IP + "?access_key=[7eb55775f303365894f741db574c7eaa]";
            var request = System.Net.WebRequest.Create(url);

            using (WebResponse wrs = request.GetResponse())
            {
                using (Stream stream = wrs.GetResponseStream())
                {
                    using (StreamReader reader = new StreamReader(stream))
                    {
                        string json = reader.ReadToEnd();
                        var obj = JObject.Parse(json);
                        string City = (string)obj["city"];
                        string Country = (string)obj["region_name"];
                        string CountryCode = (string)obj["country_code"];

                        return (CountryCode + " - " + Country + "," + City);
                    }
                }
            }


            return "";

        }

        // GET: Vets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vet == null)
            {
                return NotFound();
            }

            var vet = await _context.Vet
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vet == null)
            {
                return NotFound();
            }

            return View(vet);
        }

        // GET: Vets/Create



        public IActionResult Create()
        {
            return View();
        }

        // POST: Vets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Imie,Nazwisko,Zwierze,Objawy,Adres,Priorytet")] Vet vet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vet);
        }

        // GET: Vets/Edit/5


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vet == null)
            {
                return NotFound();
            }

            var vet = await _context.Vet.FindAsync(id);
            if (vet == null)
            {
                return NotFound();
            }
            return View(vet);
        }

        // POST: Vets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imie,Nazwisko,Zwierze,Objawy,Adres,Priorytet")] Vet vet)
        {
            if (id != vet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VetExists(vet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vet);
        }

        // GET: Vets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vet == null)
            {
                return NotFound();
            }

            var vet = await _context.Vet
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vet == null)
            {
                return NotFound();
            }

            return View(vet);
            Console.WriteLine("usunieto");
        }

        // POST: Vets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vet == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Vet'  is null.");
            }
            var vet = await _context.Vet.FindAsync(id);
            if (vet != null)
            {

                _context.Vet.Remove(vet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VetExists(int id)
        {
            return (_context.Vet?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Lab/Weterynarze/Weterynarze/Weterynarze/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInMenager
@inject UserManager<IdentityUser> UserMenager

@{
    ViewData["Title"] = "Home Page";
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Weterynarze</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Weterynarze.styles.css" asp-append-version="true" />
</head>
<body style=" background-color:white">

    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="images/logo.png" alt="">
                        <span>
                            PetMobile
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                            <ul class="navbar-nav  ">
                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Strona Główna </a>
                                </li>
                                @if (User.IsInRole("Admin") || User.IsInRole("Dystrybutor") || User.IsInRole("Weterynarz"))
                                {
                                    <li class="nav-item active">
                                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Polityka Prywatności</a>
                                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link" asp-area="" asp-controller="Vets" asp-action="Index">Zlecenia </a>
                                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link" asp-area="" asp-controller="Vets" asp-action="Location">Mapa</a>
                                    </li>
                                }


                            </ul>
                            @*<form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                            <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                            </form>*@
                        </div>

                        @*@if (User.IsInRole("Admin") || User.IsInRole("Dystrybutor") || User.IsInRole("Weterynarz"))*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="quote_btn-container  d-flex justify-content-center">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Logout">
                                    Wyloguj
                                </a>
                            </div>
                        }

                        else
                        {
                            <div class="quote_btn-container  d-flex justify-content-center">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">
                                    Rejestracja
                                </a>
                            </div>
                            <div class="quote_btn-container  d-flex justify-content-center">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">
                                    Zaloguj się
                                </a>
                            </div>
                        }



                    </div>
                </nav>
            </div>
        </header>

        <div class="container center text-center">
            <main role="main" class="pb-3">
                <br />
                @RenderBody()
            </main>
        </div>


        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>